### ISSUE TITLE
Visual Studio is unable to open the solution if there is a space in the filepath

### ISSUE THREAD

**Issue by CoreyHayward** [davidegiacometti/PowerToys-Run-VisualStudio#1]
When attempting to open a recent solution which is contained in a folder with a space the following error message appears:

![image](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/assets/72159232/adf98055-5acc-47cc-bb3c-0216400cceb5)

**Comment by davidegiacometti** [comment]
Fixed in release 0.0.5: https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/releases/tag/0.0.5
