### ISSUE TITLE
Question: Exclude specific VS Instance

### ISSUE THREAD

**Issue by LSTANCZYK** [davidegiacometti/PowerToys-Run-VisualStudio#4]
I would like for the extension to exclude specific VS instance - for example if i have VS 2019 and VS 2022 installed I only want to show VS 22 list items. How can that be achieved?

**Comment by davidegiacometti** [comment]
Hi @LSTANCZYK 

Nice idea! I have just release version [0.3.0](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/releases/tag/0.3.0) that add an option to exclude some Visual Studio versions.
You can fill it with `2019` to get rid of VS 2019 results! 😃

**Comment by LSTANCZYK** [comment]
Works like a charm. Thank you. 

I have been using VS2019 for some legacy projects and open them very rarely Once project was opened in 2019 it  was just crowding the view.

In my original issue I did not include the use case, so just for documentation purposes here it is: 
1. User has a project X that is currently using 2022 and in daily work is should open in 2022
2. One time the user needs to open old revision so they use git to check out an old commit
3. Old version only works with 2019, so the user opens it with 2019
4. User then checks out latest and continues daily work in 2022
5. Because the project was opened in 2019 this one time now it lingers in the list
6. On a daily basis now the user has to pay attention which version they open which goes against the principle of easily being able to open the project with just few keystrokes and minimal effort.
